services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/online_learning
      - JWT_SECRET=supersecretjwtkey
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
